# DOCKER

  - name: Set up the repository
    become: true
    apt:
      update_cache: yes
      name: [ca-certificates, curl, gnupg, lsb-release]
      state: latest
  
  - name: Add Dockers official GPG key
    become: true
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: true
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install Docker Engine
    become: true
    apt: 
      update_cache: yes
      name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]