# YOTTA

  - name: Update and upgrade apt packages
    become: true
    apt: 
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install packages
    become: true
    apt: 
      update_cache: yes
      name: [git, tmux, file, make, binutils]

