# ZSH

  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install packages
    become: true
    apt: 
      update_cache: yes
      name: [zsh, git, tmux]
      state: latest

  - name: set zsh as default shell
    become: yes
    user:
      name: ubuntu
      shell: /bin/zsh

  - name: download ohmyzsh installation script
    ansible.builtin.get_url:
      url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/installOmz.sh

  - name: Run ohmyzsh installation script
    ansible.builtin.shell:
      cmd: cat /tmp/installOmz.sh | sh -s -- -y
      creates: ~/.oh-my-zsh

  - name: clone mqttbay repo
    git:
      repo: https://github.com/Felix-Jacob/MQTTbay
      dest: ~/MQTTbay
      depth: 1